FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git bash make gcc musl-dev libc-dev

ENV PATH="/go/bin:/usr/local/go/bin:${PATH}"

RUN go install github.com/air-verse/air@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest

COPY api/go.mod api/go.sum ./

RUN go mod download

COPY api/ .

CMD ["air"]
