FROM golang:1.24-alpine AS dev

WORKDIR /app

RUN apk add --no-cache git bash make

ENV PATH="/go/bin:/usr/local/go/bin:${PATH}"

RUN go install github.com/air-verse/air@latest && go install github.com/swaggo/swag/cmd/swag@latest && go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY go.mod go.sum ./

RUN go mod download

CMD ["air"]
