FROM python:3.13-alpine

WORKDIR /app

RUN apk add --no-cache curl bash

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.local/bin:${PATH}"

COPY microservices/pyproject.toml .

COPY microservices/ .

RUN uv sync

EXPOSE 8054

CMD ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8054", "--reload"]