FROM python:3.13-alpine

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY microservices/pyproject.toml .
COPY microservices/uv.lock .

COPY microservices/ .

RUN uv sync --frozen --no-cache

CMD ["uv", "run", "src/main.py"]